# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-05 07:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweet_salon', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweet',
            name='createdAt',
            field=models.CharField(max_length=40),
        ),
    ]
