# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-05 07:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweet_salon', '0002_auto_20171205_0216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweet',
            name='tweetId',
            field=models.BigIntegerField(default=0, unique=True),
        ),
        migrations.AlterField(
            model_name='twitteruser',
            name='handle',
            field=models.CharField(max_length=15, unique=True),
        ),
        migrations.AlterField(
            model_name='twitteruser',
            name='userId',
            field=models.BigIntegerField(default=0, unique=True),
        ),
    ]
