# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-05 09:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweet_salon', '0003_auto_20171205_0247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweet',
            name='text',
            field=models.CharField(max_length=400),
        ),
        migrations.AlterField(
            model_name='twitteruser',
            name='displayName',
            field=models.CharField(max_length=75),
        ),
    ]
